### ISSUE TITLE
What, if anything, from the probability equations should be translatable?

### ISSUE THREAD

**Issue by jbphet** [phetsims/quantum-measurement#5]
In the design meeting on 6/4/2024 I raised the question of whether any portions of the equations and notation that convey the probability of the various outcomes on the "Coins" screen should be translatable.  The screenshots below, which are taken from the design document, highlight the areas in the design that I'm asking about.

![image](https://github.com/phetsims/quantum-measurement/assets/3082831/49d3326e-ec69-4e17-8dcc-2b0d76a97e78)

![image](https://github.com/phetsims/quantum-measurement/assets/3082831/7265ac94-7f65-4e4c-aad9-717c4cdac082)

The short term conclusion was not to support any translation at this point, and to possibly support translation of the "P", "H", and "T" characters - or some subset thereof - at some point.  @arouinfar is going to inquire with our translation network about this.

The other notation, such as the α and β characters, will not be translatable, nor will any portion of the bra and ket notation.

**Comment by jbphet** [comment]
I've removed the strings that I'd originally added for this when setting up the sim.  I can add some or all of them back as needed once we know more.  Assigning to @arouinfar for the next steps.

**Comment by arouinfar** [comment]
In the 9/10/24 design meeting we decided to continue with iconic representations (sun/moon) for the classical coin, rather than explicitly refer to heads and tails. The sun/moon characters will not be translatable.

In #24, we unified the Probability slider labels to be of the form Probability P(☼) and Probability P(↑) = |ɑ|<sup>2</sup>. The word "Probability" should be translatable, as should the character 'P', but nothing else.

**Comment by AgustinVallejo** [comment]
Those symbols now live in the constants file. It has been discussed that we should probably ask for artworks for the coins, especially since the unicode symbols don't render consistently across devices. Should that be discussed here or is this ready to close? @arouinfar
